# _config.yml
title: Jetraw Documentation
remote_theme: just-the-docs/just-the-docs
plugins: [jekyll-remote-theme]
just_the_docs:
  search_enabled: true
  #logo: /assets/logo.svg
  nav_external_links:
    - title: "Official Jetraw Manual"
      url: "https://docs.dotphoton.com/jetraw-manual/"
